In [1]:
import numpy as np
import random
import networkx as nx
from MinorityGameComplex import (Neighbors_SmallWorld, Neighbors_R, Reduced_Neighbors)
from time import time

## Draw (Network, Counts and Neighbors) and (strategies and scores)

In [32]:
S = 2
M = 2
N = 5
Ncop = 1
grado = 2
strategies0 = 2 * np.random.randint(2, size=(N, S, 2**M)) - 1
scores0 = np.random.randint(15, size=(N, S))-7
counts, neighs = Neighbors_R(N, grado)
#print('(counts, neighs) = ({}, {})'.format(counts, neighs))
imitators_now = np.array(random.sample(range(N), Ncop))
imitators_now.sort()
#counts, neighs = Reduced_Neighbors(counts, neighs, nodes_imitators)
#print('(counts, neighs)_imitators = ({}, {})'.format(counts, neighs))

In [33]:
strategies = strategies0.copy()
scores = scores0.copy()

In [36]:
node = imitators_now[0]

In [37]:
node

1

In [38]:
counts, neighs

(array([ 0,  2,  4,  6,  9, 10]), array([2, 3, 3, 4, 0, 3, 0, 1, 2, 1]))

In [39]:
scores

array([[ 0, -3],
       [-7, -3],
       [ 4,  1],
       [-5,  2],
       [ 7,  3]])

In [40]:
scores[neighs[counts[node]:counts[node+1]]]

array([[-5,  2],
       [ 7,  3]])

In [42]:
scores_max = np.argmax(scores, axis=1)
scores_min_imitators = np.argmin(scores[imitators_now], axis=1)
maxneighs = np.zeros(len(imitators_now)).astype(int)
numstratneigh = np.zeros(len(imitators_now)).astype(int)
for i in range(len(imitators_now)):
    node = imitators_now[i]
    maximoneigh = np.amax(scores[neighs[counts[node]:counts[node+1]]].flatten())
    iguales = np.argwhere(
        scores[neighs[counts[node]:counts[node+1]]].flatten() == maximoneigh).flatten()
    cual = np.random.choice(iguales)
    strat = cual%S
    neigh_con_maximo = neighs[counts[node]:counts[node+1]][int(cual/S)]
    maxneighs[i] = neigh_con_maximo
    numstratneigh[i] = strat
copy_from = np.argwhere(scores[imitators_now, scores_max[imitators_now]] < scores[
    maxneighs, numstratneigh]).flatten()
print(copy_from)
strategies[imitators_now[copy_from],scores_min_imitators[copy_from],:] = strategies[
                                    maxneighs[copy_from], numstratneigh[copy_from], :]
scores[imitators_now[copy_from], scores_min_imitators[copy_from]] = 0

[0]


In [44]:
maxneighs, numstratneigh

(array([4]), array([0]))

### Choose the same neighbors, randomly

In [445]:
chosen_neighs = np.zeros(len(counts)-1)
for i in range(len(counts) - 1):
    node = nodes_imitators[i]
    neigh_copy = np.random.choice(neighs[counts[i]:counts[i + 1]])
    chosen_neighs[i] = neigh_copy
chosen_neighs = chosen_neighs.astype(int)

# With arrays

In [446]:
strategies = strategies0.copy()
scores = scores0.copy()

In [447]:
t0=time()
scores_max = np.argmax(scores, axis=1)

scores_max_imitators = scores_max[nodes_imitators]
scores_max_neighs = scores_max[chosen_neighs]

scores_min_imitators = np.argmin(scores[nodes_imitators], axis=1)
strategies_past = strategies.copy()
copy_from = np.argwhere(scores[nodes_imitators, scores_max_imitators] < scores[
    chosen_neighs, scores_max_neighs]).flatten()
strategies[nodes_imitators[copy_from],scores_min_imitators[copy_from],:] = strategies_past[
                chosen_neighs[copy_from], scores_max_neighs[copy_from], :]
scores[nodes_imitators[copy_from], scores_min_imitators[copy_from]] = 0
print(time()-t0)

0.0024995803833007812


In [448]:
strategies_A = strategies.copy()
scores_A = scores.copy()

# With fors (less optimum)

In [449]:
strategies = strategies0.copy()
scores = scores0.copy()

In [450]:
t0 = time()
scores_max = np.argmax(scores, axis=1)
scores_min_imitators = np.argmin(scores[nodes_imitators,:], axis=1)
strategies_past = strategies.copy()
scores_past = scores.copy()
for i in range(len(counts) - 1):
    node_imit = nodes_imitators[i]
    #neigh_chosen = np.random.choice(neighs[counts[i]:counts[i + 1]])
    max_node_imit = scores_max[node_imit]
    min_node_imit = scores_min_imitators[i]
    max_chosen_neigh = scores_max[chosen_neighs[i]]
    if scores_past[node_imit, max_node_imit] < scores_past[chosen_neighs[i], max_chosen_neigh]:
        strategies[node_imit, min_node_imit] = strategies_past[chosen_neighs[i], max_chosen_neigh]
        scores[node_imit, min_node_imit] = 0
print(time()-t0)

0.00854802131652832


In [451]:
strategies_B = strategies.copy()
scores_B = scores.copy()

# Comparison

In [452]:
np.array_equal(strategies_A, strategies_B)

True

In [453]:
np.array_equal(scores_A, scores_B)

True

# Select the neighbor with highest score

In [104]:
strategies = strategies0.copy()
scores = scores0.copy()

In [102]:
scores

array([[-5, -1],
       [-3,  1],
       [-4,  0],
       [-3, -6],
       [-3, -2]])

In [106]:
scores_max = np.argmax(scores, axis=1)
scores_min_imitators = np.argmin(scores[nodes_imitators], axis=1)
maxneighs = np.zeros(len(nodes_imitators)).astype(int)
numstratneigh = np.zeros(len(nodes_imitators)).astype(int)
for i in range(len(counts) - 1):
    node = nodes_imitators[i]
    print('scores \n', scores)
    print('node ', node)
    print('neighs ', neighs[counts[i]:counts[i + 1]])
    print('scores neighs \n', scores[neighs[counts[i]:counts[i + 1]]])
    print(scores[neighs[counts[i]:counts[i + 1]]].flatten())
    maximoneigh = np.amax(scores[neighs[counts[i]:counts[i + 1]]].flatten())
    print('maximoneigh= ', maximoneigh)
    iguales = np.argwhere(
        scores[neighs[counts[i]:counts[i + 1]]].flatten() == maximoneigh).flatten()
    print('maximosiguales= ', iguales)
    cual = np.random.choice(iguales)
    print('eligo el ', cual)
    strat = cual%S
    neigh_con_maximo = neighs[counts[i]:counts[i + 1]][int(cual/S)]
    maxneighs[i] = neigh_con_maximo
    numstratneigh[i] = strat
    print('neigh, strat = ', neigh_con_maximo, strat)
    print(' ')
    
print('maxneighs= ', maxneighs)
print('numstratneigh=', numstratneigh)
copy_from = np.argwhere(scores[nodes_imitators, scores_max[nodes_imitators]] < scores[
    maxneighs, numstratneigh]).flatten()
print('strategymin imitators = ')
print(strategies[nodes_imitators[copy_from],scores_min_imitators[copy_from],:])
strategies[nodes_imitators[copy_from],scores_min_imitators[copy_from],:] = strategies[
                                    maxneighs[copy_from], numstratneigh[copy_from], :]
print('new strategymin imitators = ')
print(strategies[nodes_imitators[copy_from],scores_min_imitators[copy_from],:])
scores[nodes_imitators[copy_from], scores_min_imitators[copy_from]] = 0
print('scores')
print(scores)

scores 
 [[-5 -1]
 [-3  1]
 [-4  0]
 [-3 -6]
 [-3 -2]]
node  1
neighs  [0 2 3 4]
scores neighs 
 [[-5 -1]
 [-4  0]
 [-3 -6]
 [-3 -2]]
[-5 -1 -4  0 -3 -6 -3 -2]
maximoneigh=  0
maximosiguales=  [3]
eligo el  3
neigh, strat =  2 1
 
scores 
 [[-5 -1]
 [-3  1]
 [-4  0]
 [-3 -6]
 [-3 -2]]
node  2
neighs  [0 1 3 4]
scores neighs 
 [[-5 -1]
 [-3  1]
 [-3 -6]
 [-3 -2]]
[-5 -1 -3  1 -3 -6 -3 -2]
maximoneigh=  1
maximosiguales=  [3]
eligo el  3
neigh, strat =  1 1
 
maxneighs=  [2 1]
numstratneigh= [1 1]
strategymin imitators = 
[[ 1 -1  1  1]]
new strategymin imitators = 
[[1 1 1 1]]
scores
[[-5 -1]
 [-3  1]
 [ 0  0]
 [-3 -6]
 [-3 -2]]


In [5]:
imitators = np.array([1,15,23,50,98])

In [25]:
who_now = np.random.rand(5)
who_now

array([0.04644362, 0.48342698, 0.40955269, 0.15872487, 0.58787192])

In [11]:
who_now>0.6

array([ True, False,  True, False, False])

In [13]:
1/1000

0.001

In [38]:
for i in range(1000):
    who_now = np.random.rand(5)
    if len(imitators[who_now<0.001])>0:
        print(imitators[who_now<0.001])

[23]
[98]
[98]
[1]
[15]


In [11]:
S = 2
M = 2
N = 6
Ncop = 2

grado = 3
k = N*grado/2

strategies0 = 2 * np.random.randint(2, size=(N, S, 2**M)) - 1
scores0 = np.random.randint(15, size=(N, S))-7
#counts, neighs = Neighbors_SmallWorld(N, p)
counts, neighs = Neighbors_R(N, grado)
#print('(counts, neighs) = ({}, {})'.format(counts, neighs))
nodes_imitators = np.array(random.sample(range(N), Ncop))
nodes_imitators.sort()
counts, neighs = Reduced_Neighbors(counts, neighs, nodes_imitators)
#print('(counts, neighs)_imitators = ({}, {})'.format(counts, neighs))